### ISSUE TITLE
Failed to get resource

### ISSUE THREAD

**Issue by josealfonsomora** [littlerobots/version-catalog-update-plugin#87] opened 2022-09-05 17:09 UTC
**Describe the issue**
Having errors and long builds executing `./gradlew versionCatalogUpdate --info`:
```Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://s3.amazonaws.com/salesforcesos.com/android/maven/release/org/jetbrains/kotlin/kotlin-parcelize-runtime/maven-metadata.xml)]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://s3.amazonaws.com/salesforcesos.com/android/maven/release/com/google/android/material/material/maven-metadata.xml)]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://s3.amazonaws.com/salesforcesos.com/android/maven/release/androidx/core/core-ktx/maven-metadata.xml)]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://s3.amazonaws.com/salesforcesos.com/android/maven/release/androidx/core/core-splashscreen/maven-metadata.xml)]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://s3.amazonaws.com/salesforcesos.com/android/maven/release/androidx/appcompat/appcompat/maven-metadata.xml)]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://s3.amazonaws.com/salesforcesos.com/android/maven/release/androidx/navigation/navigation-fragment-ktx/maven-metadata.xml)]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://s3.amazonaws.com/salesforcesos.com/android/maven/release/androidx/lifecycle/lifecycle-runtime-ktx/maven-metadata.xml)]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://s3.amazonaws.com/salesforcesos.com/android/maven/release/androidx/lifecycle/lifecycle-extensions/maven-metadata.xml)]
Failed to get resource: GET. [HTTP HTTP/1.1 403 Forbidden: https://s3.amazonaws.com/salesforcesos.com/android/maven/release/androidx/constraintlayout/constraintlayout/maven-metadata.xml)]
```

I think having custom urls for maven is doing this and the plugin is trying all the url with the consequent error

After a long build time it works

**Steps to reproduce**

build.gradle with

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        maven { url "https://salesforce-marketingcloud.github.io/MarketingCloudSDK-Android/repository" }
        maven { url "https://s3.amazonaws.com/salesforcesos.com/android/maven/release" }
    }
}
```

**Stacktrace**
Please run Gradle with the `--stacktrace` option and share the output in case of a Gradle error.

**Comment by hvisser** [comment] 2022-09-05 17:30
This is an issue with how you have setup your plugin repositories...Normally `gradlePluginPortal()` should be available for all plugins, but maybe you've overridden the plugin repositories in your `settings.gradle`. Make sure you have something like this in `settings.gradle` (quoting the README):

```
pluginManagement {
    repositories {
      mavenCentral()
    }
}
```

If you already have that block you should add `mavenCentral()` or `gradlePluginPortal()` there.

**Comment by josealfonsomora** [comment] 2022-09-06 08:14
Thanks for your response Hugo.  I believe is related to [this](https://github.com/ben-manes/gradle-versions-plugin/issues/505)

**Comment by hvisser** [comment] 2022-09-06 08:33
A right I must have misread the error, it seems to be skipping the repositories or not resolving through the `google()` repository, but in any case I don't think there's much I can do here. It's either a Gradle setup thing or an issue with the dependency versions plugin.

You could try specifying the specific artifacts that it should fetch from jitpack and salesforce repositories using [inclusion filters](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:repository-content-filtering), which is probably a good idea anyway, because it doesn't make sense to hit those repositories for artifacts they will never have, and you want to prevent getting non-official versions of artifacts from repositories that shouldn't have them.

**Comment by hvisser** [comment] 2022-09-07 09:26
Closing since I don't think there's anything that can or needs to be done as the issue is not actually happening in the plugin itself.

**Closed by hvisser** 2022-09-07 09:26 UTC
