### ISSUE TITLE
Getting following exception while upgrading catalogue version

### ISSUE THREAD

**Issue by shk2123** [littlerobots/version-catalog-update-plugin#84] opened 2022-08-25 05:53 UTC
Exception-
nl.littlerobots.vcu.model.VersionDefinition$Unspecified cannot be cast to nl.littlerobots.vcu.model.VersionDefinition$Simple

P.S. - Reports are getting generated, and then it fails with this exception

**Comment by hvisser** [comment] 2022-08-25 07:43
This is a duplicate of #82 which is fixed in the current snapshot, so that will be fixed in the next release.

**Closed by hvisser** 2022-08-25 07:43 UTC
